# This is for development only
# Do not use this
#
#
#  /$$$$$$$                  /$$   /$$             /$$           /$$$$$$$$             /$$
# | $$__  $$                | $$$ | $$            | $$          | $$_____/            | $$
# | $$  \ $$  /$$$$$$       | $$$$| $$  /$$$$$$  /$$$$$$        | $$       /$$$$$$$  /$$$$$$    /$$$$$$   /$$$$$$
# | $$  | $$ /$$__  $$      | $$ $$ $$ /$$__  $$|_  $$_/        | $$$$$   | $$__  $$|_  $$_/   /$$__  $$ /$$__  $$
# | $$  | $$| $$  \ $$      | $$  $$$$| $$  \ $$  | $$          | $$__/   | $$  \ $$  | $$    | $$$$$$$$| $$  \__/
# | $$  | $$| $$  | $$      | $$\  $$$| $$  | $$  | $$ /$$      | $$      | $$  | $$  | $$ /$$| $$_____/| $$
# | $$$$$$$/|  $$$$$$/      | $$ \  $$|  $$$$$$/  |  $$$$/      | $$$$$$$$| $$  | $$  |  $$$$/|  $$$$$$$| $$
# |_______/  \______/       |__/  \__/ \______/    \___/        |________/|__/  |__/   \___/   \_______/|__/
#
#
#
wireguard_configs:
    # For James
  - NAME: jameso
    PORT: 51822
    PEER_PUBLIC_KEY: nj5rB0CIL6JUXLvl+oqQXcav2qnr509FzpF30lF8mEY=
    INTERFACE_ADDRESS: "10.70.248.2/31"
    # For vpn
  - NAME: ghvpn
    PORT: 51837
    PEER_PUBLIC_KEY: 0vrESEv5ACnVVY20Jzk2na4Twfk+Gk+OMU9rqO6c6AM=
    INTERFACE_ADDRESS: "10.70.248.30/31"

  - NAME: nn177dev
    PORT: 51913
    PEER_PUBLIC_KEY: nA+MQsqlZBSsa3KYhhQe1YphG4pStfRn2DzeHIoZyFI=
    INTERFACE_ADDRESS: "10.70.248.177/30"
    NEIGHBORS: "10.70.248.178"
    TX_LENGTH: 1420
    COST: 30
    BFD_ENABLE: true
    BFD_INTERVAL: 1000ms
    BFD_MULTIPLIER: 10
