wireguard_configs:

## OSPF Connections

    # For the super awesome remote hub NN592
  - NAME: nn592
    PORT: 51821
    PEER_PUBLIC_KEY: sD3bVQglZfq2j82or48q+i0R0KdszUPZRkcz4rVqAk8=
    INTERFACE_ADDRESS: "10.70.247.121/30"
    NEIGHBORS: "10.70.247.122"
    TX_LENGTH: 1420
    COST: 99

    # For Andrew Dickinson Amazon VPC
  - NAME: andrewvpc
    PORT: 51825
    PEER_PUBLIC_KEY: 2uMY2He1KCRjnsXnKU4KVD6dfCXzUUxly117aXsZ3kc=
    INTERFACE_ADDRESS: "10.70.247.125/30"
    NEIGHBORS: "10.70.247.126"
    TX_LENGTH: 1366
    COST: 170

### Road Warriors

    # For James
  - NAME: jameso
    PORT: 51822
    PEER_PUBLIC_KEY: nj5rB0CIL6JUXLvl+oqQXcav2qnr509FzpF30lF8mEY=
    INTERFACE_ADDRESS: "10.70.247.0/31"

    # For Matt
  - NAME: matt
    PORT: 51823
    PEER_PUBLIC_KEY: JQ9/0Ll0oCsq1F5EHXomnoKiaSnvGX9b2RH4KfRq7Us=
    INTERFACE_ADDRESS: "10.70.247.2/31"

    # For JohnB
  - NAME: johnb
    PORT: 51824
    PEER_PUBLIC_KEY: JOHNBcSeEXKV7l6KEi9ktxoKiFh6CymdfZ3ItDZCxRk=
    INTERFACE_ADDRESS: "10.70.247.4/31"
