wireguard_configs:

## OSPF Connections

    # For the super awesome remote hub NN592
  - NAME: nn592
    PORT: 51821
    PEER_PUBLIC_KEY: sD3bVQglZfq2j82or48q+i0R0KdszUPZRkcz4rVqAk8=
    INTERFACE_ADDRESS: "10.70.247.121/30"
    NEIGHBORS: "10.70.247.122"
    TX_LENGTH: 1420
    COST: 99

    # For Andrew Dickinson Amazon VPC
  - NAME: andrewvpc
    PORT: 51825
    PEER_PUBLIC_KEY: 2uMY2He1KCRjnsXnKU4KVD6dfCXzUUxly117aXsZ3kc=
    INTERFACE_ADDRESS: "10.70.247.125/30"
    NEIGHBORS: "10.70.247.126"
    TX_LENGTH: 1366
    COST: 130

    # For Matt B 777
  - NAME: nn777
    PORT: 51827
    PEER_PUBLIC_KEY: KLuwfaUdugySPhNAtOpdBDQeplvt0vaqioWBFtTCcAo=
    INTERFACE_ADDRESS: "10.70.247.129/30"
    NEIGHBORS: "10.70.247.130"
    TX_LENGTH: 1420
    COST: 198
    BFD_ENABLE: true
    BFD_INTERVAL: 500ms
    BFD_MULTIPLIER: 10

    # For Soft Surplus 1417
  - NAME: nn1417
    PORT: 51828
    PEER_PUBLIC_KEY: VGIoIuqIfM+lZt1rgJ9WZzu9n6qn7+YWFn2W/GvmGxo=
    INTERFACE_ADDRESS: "10.70.247.133/30"
    NEIGHBORS: "10.70.247.134"
    TX_LENGTH: 1420
    COST: 26

    # For nn7800 CCNY
  - NAME: nn7800
    PORT: 51831
    PEER_PUBLIC_KEY: QPu1xed/4VgghL7QFcYFLgN5c+bw6XfPEFwdg8tebzw=
    INTERFACE_ADDRESS: "10.70.247.137/30"
    NEIGHBORS: "10.70.247.138"
    TX_LENGTH: 1420
    COST: 30
    BFD_ENABLE: true
    BFD_INTERVAL: 500ms
    BFD_MULTIPLIER: 10

    # Monique laptop
  - NAME: moniquelaptop
    PORT: 51833
    PEER_PUBLIC_KEY: LbjNQE6mwaC5v1zlLRDMBqeUC30ta/Cv4xgcW5U46ko=
    INTERFACE_ADDRESS: "10.70.247.141/30"

### Road Warriors

    # For James
  - NAME: jameso
    PORT: 51822
    PEER_PUBLIC_KEY: nj5rB0CIL6JUXLvl+oqQXcav2qnr509FzpF30lF8mEY=
    INTERFACE_ADDRESS: "10.70.247.0/31"

    # For Matt
  - NAME: matt
    PORT: 51823
    PEER_PUBLIC_KEY: JQ9/0Ll0oCsq1F5EHXomnoKiaSnvGX9b2RH4KfRq7Us=
    INTERFACE_ADDRESS: "10.70.247.2/31"

    # For JohnB
  - NAME: johnb
    PORT: 51824
    PEER_PUBLIC_KEY: JOHNBcSeEXKV7l6KEi9ktxoKiFh6CymdfZ3ItDZCxRk=
    INTERFACE_ADDRESS: "10.70.247.4/31"

    # For Olivier
  - NAME: olivier
    PORT: 51826
    PEER_PUBLIC_KEY: Kak4TThChfbK+jzzvXsdoVgFvAb082uqI2PIVdCMD1c=
    INTERFACE_ADDRESS: "10.70.247.6/31"

    # Lydon Laptop
  - NAME: lydonlaptop
    PORT: 51829
    PEER_PUBLIC_KEY: 2Zi8ePpTkUOoBvAhQQ+cDFxBE/IMLGNF3gV56PgjtlY=
    INTERFACE_ADDRESS: "10.70.247.8/31"

    # Matt Travel Unifi
  - NAME: mattUnifi
    PORT: 51830
    PEER_PUBLIC_KEY: MI9moamBMS1+9pW5urL0+IwfDjJC7jJ0mEqvX0aP8W4=
    INTERFACE_ADDRESS: "10.70.247.10/31"

    # Lekhya Road warrior
  - NAME: Lekhya
    PORT: 51832
    PEER_PUBLIC_KEY: 6KuYC/GlvS+TyOenz1wNkRjHXSSjkoACQVYbPPkd4G4=
    INTERFACE_ADDRESS: "10.70.247.12/31"

    # Jason Road warrior
  - NAME: jason
    PORT: 51834
    PEER_PUBLIC_KEY: Q7k2E1wb9DU9kiTAtsu0EIXqyeITtKwQQkmpyA2R208=
    INTERFACE_ADDRESS: "10.70.247.14/31"
