wireguard_configs:

## OSPF Connections

    # For the super awesome remote hub NN592
  - NAME: nn592
    PORT: 51821
    PEER_PUBLIC_KEY: sD3bVQglZfq2j82or48q+i0R0KdszUPZRkcz4rVqAk8=
    INTERFACE_ADDRESS: "10.70.246.121/30"
    NEIGHBORS: "10.70.246.122"
    TX_LENGTH: 1420
    COST: 99

### Road Warriors

    # For James
  - NAME: jameso
    PORT: 51822
    PEER_PUBLIC_KEY: nj5rB0CIL6JUXLvl+oqQXcav2qnr509FzpF30lF8mEY=
    INTERFACE_ADDRESS: "10.70.246.0/31"

    # For Matt
  - NAME: matt
    PORT: 51823
    PEER_PUBLIC_KEY: JQ9/0Ll0oCsq1F5EHXomnoKiaSnvGX9b2RH4KfRq7Us=
    INTERFACE_ADDRESS: "10.70.246.2/31"

    # For JohnB
  - NAME: johnb
    PORT: 51824
    PEER_PUBLIC_KEY: JOHNBcSeEXKV7l6KEi9ktxoKiFh6CymdfZ3ItDZCxRk=
    INTERFACE_ADDRESS: "10.70.246.4/31"

    # For Daniel
  - NAME: daniel
    PORT: 51825
    PEER_PUBLIC_KEY: czvx7yuWaT7qISYLd+gwcbW8AQUDMI6/gYOj7gz4Jl4=
    INTERFACE_ADDRESS: "10.70.246.6/31"

    ### Site-to-site

    # SN10 -> SN3
  - NAME: sn3
    PORT: 51803
    PEER_PUBLIC_KEY: HCYsMu1Wztk8ape2WP5HYiFZnNpn07guRNvKZw/e0mk=
    PEER_ENDPOINT: "199.170.132.43:51811"
    INTERFACE_ADDRESS: "10.70.183.6/30"
    NEIGHBORS: "10.70.183.5"
    TX_LENGTH: 1420
    COST: 70

    # SN11 -> SN10
  - NAME: sn10
    PORT: 51810
    PEER_PUBLIC_KEY: wFQXW68D0ePLU39A1yfuIRH7oyH3ZIfb424OczjI7Ak=
    PEER_ENDPOINT: "23.158.16.28:51811"
    INTERFACE_ADDRESS: "10.70.183.10/30"
    NEIGHBORS: "10.70.183.9"
    TX_LENGTH: 1420
    COST: 80
