wireguard_configs:
    ### Remote Hubs

    # For the super awesome remote hub NN592
  - NAME: nn592
    PORT: 51821
    PEER_PUBLIC_KEY: sD3bVQglZfq2j82or48q+i0R0KdszUPZRkcz4rVqAk8=
    INTERFACE_ADDRESS: "10.70.250.121/30"
    NEIGHBORS: "10.70.250.122"
    TX_LENGTH: 1420
    COST: 99

    # For NN135 RobJ (SN3 migration)
  - NAME: nn135
    PORT: 51900
    PEER_PUBLIC_KEY: V/wrXElkbVD13EJEJ6MfiBPyNH8ArBftbReH2NeIfkg=
    INTERFACE_ADDRESS: "10.70.250.125/30"
    NEIGHBORS: "10.70.250.126"
    TX_LENGTH: 1420
    COST: 41

    # For NN136 AndyB Amazon VPC (SN3 migration)
  - NAME: nn136
    PORT: 51901
    PEER_PUBLIC_KEY: BiII3RZxHQoYeWaeNrI0HVJBze1oO+9bcoWO59DWJlw=
    INTERFACE_ADDRESS: "10.70.250.129/30"
    NEIGHBORS: "10.70.250.130"
    TX_LENGTH: 1420
    COST: 10

    # For NN1417 Soft Surplus/Hex House (SN3 migration)
  - NAME: nn1417
    PORT: 51902
    PEER_PUBLIC_KEY: hK3Vpdos7sMIWhOMqOvWvBNLrKbyw7pEfDdOI1wobRA=
    INTERFACE_ADDRESS: "10.70.250.133/30"
    NEIGHBORS: "10.70.250.134"
    TX_LENGTH: 1420
    COST: 28

    # For NN148 Harlem Kiosk (SN3 migration)
  - NAME: nn148
    PORT: 51903
    PEER_PUBLIC_KEY: Qpx9x8eQ0/M3pKo5MQTA1dg0wFKOjo8kNh0iJxeiZ1U=
    INTERFACE_ADDRESS: "10.70.250.137/30"
    NEIGHBORS: "10.70.250.138"
    TX_LENGTH: 1420
    COST: 80

    # For NN2299 Lily House (SN3 migration)
  - NAME: nn2299
    PORT: 51904
    PEER_PUBLIC_KEY: o6xGrijkBrzhPNdDAiESpTk0Mjn68ASpQJH+0dHtJRA=
    INTERFACE_ADDRESS: "10.70.250.141/30"
    NEIGHBORS: "10.70.250.142"
    TX_LENGTH: 1420
    COST: 110

    # For NN317 Temkin (SN3 migration)
  - NAME: nn317
    PORT: 51905
    PEER_PUBLIC_KEY: WCJap7m+hhUI41O+2v3iI9UiFz5hXpRrCcIi6vUHYHU=
    INTERFACE_ADDRESS: "10.70.250.145/30"
    NEIGHBORS: "10.70.250.146"
    TX_LENGTH: 1420
    COST: 99

    # For NN329 Simona (SN3 migration)
  - NAME: nn329
    PORT: 51906
    PEER_PUBLIC_KEY: BwGzJInFuBR4sQI8eUk5TH5ZZvDI952abbHoEyXLcRc=
    INTERFACE_ADDRESS: "10.70.250.149/30"
    NEIGHBORS: "10.70.250.150"
    TX_LENGTH: 1420
    COST: 40

    # For NN383 Piotr (SN3 migration)
  - NAME: nn383
    PORT: 51907
    PEER_PUBLIC_KEY: wqq0bzKjsMAfRWEBdqAu/AG9IqNyvBziElz/AbsVzh4=
    INTERFACE_ADDRESS: "10.70.250.153/30"
    NEIGHBORS: "10.70.250.154"
    TX_LENGTH: 1420
    COST: 99

    # For NN640 YAYB (SN3 migration)
  - NAME: nn640
    PORT: 51908
    PEER_PUBLIC_KEY: MK8l7PMsQ/+Jz8Ul56BJLxrubj08f3jscKzMfVfRZQ0=
    INTERFACE_ADDRESS: "10.70.250.157/30"
    NEIGHBORS: "10.70.250.158"
    TX_LENGTH: 1420
    COST: 45

    # For NN666 JohnB Home (SN3 migration)
  - NAME: nn666
    PORT: 51909
    PEER_PUBLIC_KEY: JOHnBoxVAAH4JcL0QZbKYyuXP5WQzeSU3UIwXlRuzhA=
    INTERFACE_ADDRESS: "10.70.250.161/30"
    NEIGHBORS: "10.70.250.162"
    TX_LENGTH: 1420
    COST: 99

    # For NN777 MattB Pine Plains (SN3 migration)
  - NAME: nn777
    PORT: 51910
    PEER_PUBLIC_KEY: wUm8/urU56aHwE8I2voR4Pm/Y0rIJ2bD70wo+X//yX8=
    INTERFACE_ADDRESS: "10.70.250.165/30"
    NEIGHBORS: "10.70.250.166"
    TX_LENGTH: 1420
    COST: 200

    # For Andrew Dickinson Amazon VPC (SN3 migration)
  - NAME: andrewvpc
    PORT: 51911
    PEER_PUBLIC_KEY: 2uMY2He1KCRjnsXnKU4KVD6dfCXzUUxly117aXsZ3kc=
    INTERFACE_ADDRESS: "10.70.250.169/30"
    NEIGHBORS: "10.70.250.170"
    TX_LENGTH: 1420
    COST: 150

    # For nn584 Olmsted until the SN11 VPN is up
  - NAME: nn584
    PORT: 51912
    PEER_PUBLIC_KEY: jO3369P+BFpmJfJKz4rvJ3+9mqM3IztiA5lZpGAaTCA=
    INTERFACE_ADDRESS: "10.70.250.173/30"
    NEIGHBORS: "10.70.250.174"
    TX_LENGTH: 1420
    COST: 100

    # For NN177 Josh 8531 (SN3 migration)
  - NAME: nn177
    PORT: 51913
    PEER_PUBLIC_KEY: nA+MQsqlZBSsa3KYhhQe1YphG4pStfRn2DzeHIoZyFI=
    INTERFACE_ADDRESS: "10.70.250.177/30"
    NEIGHBORS: "10.70.250.178"
    TX_LENGTH: 1420
    COST: 30
    BFD_ENABLE: true
    BFD_INTERVAL: 500ms
    BFD_MULTIPLIER: 10

    # For hEX LTE Hotspot 8201 (SN3 migration)
  - NAME: nn8201
    PORT: 51914
    PEER_PUBLIC_KEY: v84VGCperE/HYZY3b4DANIMSSeZaC81rNH+1rqerBi8=
    INTERFACE_ADDRESS: "10.70.250.181/30"
    NEIGHBORS: "10.70.250.182"
    TX_LENGTH: 1420
    COST: 200

    # For NN692 Olivier (SN3 migration)
  - NAME: nn692
    PORT: 51915
    PEER_PUBLIC_KEY: wiMZmM9gVevdA9LSTb8D2Lmi4w5tzFyiCPswNY9213M=
    INTERFACE_ADDRESS: "10.70.250.185/30"
    NEIGHBORS: "10.70.250.186"
    TX_LENGTH: 1420
    COST: 15

    # NOTE: the next available IP is "10.70.250.189/30" :)

    ### Road Warriors

    # For Daniel Heredia
  - NAME: danielheredia
    PORT: 51823
    PEER_PUBLIC_KEY: czvx7yuWaT7qISYLd+gwcbW8AQUDMI6/gYOj7gz4Jl4=
    INTERFACE_ADDRESS: "10.70.250.0/31"

    # For James
  - NAME: jameso
    PORT: 51822
    PEER_PUBLIC_KEY: nj5rB0CIL6JUXLvl+oqQXcav2qnr509FzpF30lF8mEY=
    INTERFACE_ADDRESS: "10.70.250.2/31"

    # For deploying https://github.com/nycmeshnet/nyckml
  - NAME: ghnyckml
    PORT: 51824
    PEER_PUBLIC_KEY: eOs2ZTnjuhNCchSJcwYwVecrN0pTxASAhSof/81Y7wo=
    INTERFACE_ADDRESS: "10.70.250.4/31"

    # For deploying https://github.com/nycmeshnet/nycmesh-dns
  - NAME: ghdns
    PORT: 51825
    PEER_PUBLIC_KEY: eF3Cp1GmhdpbUfeZoEBkkUaxnhmVeWMwlfYJ0+/13zE=
    INTERFACE_ADDRESS: "10.70.250.6/31"

    # For deploying https://github.com/nycmeshnet/k8s-infra
  - NAME: ghk8sinfra
    PORT: 51826
    PEER_PUBLIC_KEY: ZDxi2CwlraP/U/lwLGezQoJBDNtozxpomhpe0z2F8Rc=
    INTERFACE_ADDRESS: "10.70.250.8/31"

    # For deploying https://github.com/nycmeshnet/meshdb
  - NAME: ghmeshdb
    PORT: 51827
    PEER_PUBLIC_KEY: u7CW7SfIWBpxuCEs3MNjESBN/7AlMVkMkUAFFAQcKH8=
    INTERFACE_ADDRESS: "10.70.250.10/31"

    # For deploying https://github.com/nycmeshnet/meshforms
  - NAME: ghmeshforms
    PORT: 51828
    PEER_PUBLIC_KEY: AptusHJ6npTqJSBNkDF/NnXoSDiC4wwXLPHC0o2Zmic=
    INTERFACE_ADDRESS: "10.70.250.12/31"

    # For deploying https://github.com/nycmeshnet/meshdb-line-of-sight
  - NAME: ghlos
    PORT: 51829
    PEER_PUBLIC_KEY: YHCLZV4l+3JSmcfki6QuMP3OjXNnAknSVj9I6EmKjE8=
    INTERFACE_ADDRESS: "10.70.250.14/31"

    # For deploying https://github.com/nycmeshnet/network-map
  - NAME: ghnetworkmap
    PORT: 51830
    PEER_PUBLIC_KEY: 2CMYxIIJBA79SEHxrK3MMw7FROJzaFa60agTbkchCSI=
    INTERFACE_ADDRESS: "10.70.250.16/31"

    # For deploying https://github.com/nycmeshnet/ntp-infra
  - NAME: ghntp
    PORT: 51831
    PEER_PUBLIC_KEY: Hq5Oc1QnRPeIQ1Wm5kbXoEecjWfv/xwY415T4erw8RQ=
    INTERFACE_ADDRESS: "10.70.250.18/31"

    # For deploying https://github.com/nycmeshnet/mesh-services-monitoring
  - NAME: ghmsm
    PORT: 51832
    PEER_PUBLIC_KEY: mKgsPQo7IiFNmqDwt3qD2R3QaLDkOTzyRUxHhuS9gRk=
    INTERFACE_ADDRESS: "10.70.250.20/31"

    # For deploying https://github.com/nycmeshnet/nycmesh-monitoring-infra
  - NAME: ghmoninfra
    PORT: 51833
    PEER_PUBLIC_KEY: UfBvVEBK1eka6Xade0Qk+tV6k9xaHLInrr1KVCWj5kI=
    INTERFACE_ADDRESS: "10.70.250.22/31"

    # For deploying https://github.com/nycmeshnet/syslog-infra
  - NAME: ghsyslog
    PORT: 51834
    PEER_PUBLIC_KEY: M1Igs2m45IzawVKlqU9Ds3oh0GH7VdLJzZ55JsrL8XQ=
    INTERFACE_ADDRESS: "10.70.250.24/31"

    # For deploying https://github.com/nycmeshnet/wiki-infra
  - NAME: ghwiki
    PORT: 51835
    PEER_PUBLIC_KEY: pOnlg0ffpWnVvgITdi/xB/waEGrAC0qCQhHPvz/W4hM=
    INTERFACE_ADDRESS: "10.70.250.26/31"

    # For deploying https://github.com/nycmeshnet/map-infra
  - NAME: ghmap
    PORT: 51836
    PEER_PUBLIC_KEY: 6AJ2gbClwA+nT/H+WU2xKgmKvaVqu2/IgMcoDBe2jTs=
    INTERFACE_ADDRESS: "10.70.250.28/31"

    # For deploying https://github.com/nycmeshnet/vpn-infra
  - NAME: ghvpn
    PORT: 51837
    PEER_PUBLIC_KEY: 0vrESEv5ACnVVY20Jzk2na4Twfk+Gk+OMU9rqO6c6AM=
    INTERFACE_ADDRESS: "10.70.250.30/31"

    # For brooks home router (SN1 migration)
  - NAME: brooks
    PORT: 51838
    PEER_PUBLIC_KEY: Kbgk7cVNaD5mkebSqDTVWl4eLWCk8teXjKGnzoIjR1s=
    INTERFACE_ADDRESS: "10.70.250.32/31"

    # For Gabe Conradi #5712 (SN1 migration)
  - NAME: gabeconradi
    PORT: 51839
    PEER_PUBLIC_KEY: b20eXLSYLYggN+0gTuySM5ulXpZKIhwJffwLabzyQjQ=
    INTERFACE_ADDRESS: "10.70.250.34/31"

    # For Scott145 (SN1 migration)
  - NAME: scott145
    PORT: 51840
    PEER_PUBLIC_KEY: XzmCz5lHr53FMzBjGCGVKf51UdpiZuIjQXph9QN57Cw=
    INTERFACE_ADDRESS: "10.70.250.36/31"

    # For Akash Kumar (SN1 migration)
  - NAME: akashkumar
    PORT: 51841
    PEER_PUBLIC_KEY: 6vTPbcZcJP3UsHG73uTdhKhNOb0ztGFdL81WDFOYeW0=
    INTERFACE_ADDRESS: "10.70.250.38/31"

    # For Quincy Blake (SN1 migration)
  - NAME: quincyblake
    PORT: 51842
    PEER_PUBLIC_KEY: S/shgmksUJffBvnDsWcOcunJkPca4mcaVxkYOsKYtnY=
    INTERFACE_ADDRESS: "10.70.250.40/31"

    # For Matthew Boyd (SN1 migration)
  - NAME: matthewboyd
    PORT: 51843
    PEER_PUBLIC_KEY: 4AHMI3ARAtlM+pDLcqkmJl7CKewdjdzeK/gHNcjwk2c=
    INTERFACE_ADDRESS: "10.70.250.42/31"

    # For Matt B Pine Plains (777 no ospf) (SN1 migration)
  - NAME: mattbpin
    PORT: 51844
    PEER_PUBLIC_KEY: dHr8IpqvJUziNCp6Uh2u75qqBtiHVPPjZFpwWahNuQM=
    INTERFACE_ADDRESS: "10.70.250.44/31"

    # For Ezra (SN1 migration)
  - NAME: ezri
    PORT: 51845
    PEER_PUBLIC_KEY: kUjG+vika8cCIbwYYUm+L2CwyWYU4vaS3GAa/c9LZXc=
    INTERFACE_ADDRESS: "10.70.250.46/31"

    # For Willard Nilges (SN1 migration)
  - NAME: willardnilges
    PORT: 51846
    PEER_PUBLIC_KEY: iLPG+70qOqfVLses9V9Q/q5aXFhJQiIRoVNO6QWaxDQ=
    INTERFACE_ADDRESS: "10.70.250.48/31"

    # Angelo NN691/693/695 second connection (SN1 migration)
  - NAME: angelosecond
    PORT: 51847
    PEER_PUBLIC_KEY: aswrRcAKSf1BW3TLTR+A6tvuObHShW5m29EyF/UZ5Tw=
    INTERFACE_ADDRESS: "10.70.250.50/31"

    # micro (SN1 migration)
  - NAME: micro
    PORT: 51848
    PEER_PUBLIC_KEY: MESHNMbP35GLY6EYNXFM7wZ+LXIDrHacwX9qvOX+WCg=
    INTERFACE_ADDRESS: "10.70.250.52/31"

    # For JohnB pfSense (SN1 migration)
  - NAME: johnbpfsense
    PORT: 51849
    PEER_PUBLIC_KEY: oJohnbidqbuvpmYWBqNuTUp++XbKxWWP/V/b0+lVrjY=
    INTERFACE_ADDRESS: "10.70.250.54/31"

    # For JohnB phone/laptop (SN1 migration)
  - NAME: johnbphonelap
    PORT: 51850
    PEER_PUBLIC_KEY: voAjohnbLEiyFZK2Z95LZf8cZB/z4aLAtzau5DBDCww=
    INTERFACE_ADDRESS: "10.70.250.56/31"

    # For Angelo NN691/693/695 (SN1 migration)
  - NAME: angelo
    PORT: 51851
    PEER_PUBLIC_KEY: 8yZRetpQLZWqOpJhWsrL+jU1zuC4qAmCM0i3OkfjDgQ=
    INTERFACE_ADDRESS: "10.70.250.58/31"

    # Josh 8531 (NN177) - FiOS Router (SN1 migration)
  - NAME: josh8531fios
    PORT: 51852
    PEER_PUBLIC_KEY: ib566wUAZjrdzD4y1fXTvmkb/54J+5jrMIoEIz3QLDc=
    INTERFACE_ADDRESS: "10.70.250.60/31"

    # For Josh 8531 (NN177) - Mobile (SN1 migration)
  - NAME: josh8531mobil
    PORT: 51853
    PEER_PUBLIC_KEY: iOzqcXxAy23ccpDUZkdEobvgYgQRdQ74VWC8WiptUyM=
    INTERFACE_ADDRESS: "10.70.250.62/31"

    # For eaon / MZ (SN1 migration)
  - NAME: eaonmz
    PORT: 4500
    PEER_PUBLIC_KEY: 7YLq4CrycYYRP4YdZ5cjiPozaWyNCXa6kKlFgSH2SwU=
    INTERFACE_ADDRESS: "10.70.250.64/31"

    # For Alessandro new (SN1 migration)
  - NAME: alessandro
    PORT: 51854
    PEER_PUBLIC_KEY: iH0f4aAMGPgSyD9Q1M5Cr3//NQaut5tVdtFqz2XT9Ao=
    INTERFACE_ADDRESS: "10.70.250.66/31"

    # For Alessandro new (SN1 migration)
  - NAME: alessandrino
    PORT: 51855
    PEER_PUBLIC_KEY: aRrCytJl1zpD78jBzz0Pf134XgiozNxxOI9MzVncnRc=
    INTERFACE_ADDRESS: "10.70.250.68/31"

    # For Olivier (SN1 migration)
  - NAME: olivier
    PORT: 51856
    PEER_PUBLIC_KEY: WlJqtSIHFeoei+QsDdqCCeJFNEC8H6quGMjw1so+MQ4=
    INTERFACE_ADDRESS: "10.70.250.70/31"

    # For Aubergine (SN1 migration)
  - NAME: aubergine
    PORT: 51857
    PEER_PUBLIC_KEY: INkZww2NKvOhOdvexcLvn7hef/Wc+6onyQC5ql5UFQ8=
    INTERFACE_ADDRESS: "10.70.250.72/31"

    # For Zachs phone (SN1 migration)
  - NAME: zachsphone
    PORT: 51858
    PEER_PUBLIC_KEY: 68uANGo0M2jv5LcB6rFYmM3h6y6qI9mdHo+/B8RjvQY=
    INTERFACE_ADDRESS: "10.70.250.74/31"

    # For Zach bonnie (SN1 migration)
  - NAME: zachbonnie
    PORT: 51859
    PEER_PUBLIC_KEY: OEUnHbDnSx0XBpNiI6McBvfCqwxtxHb10u1vlhcf/HY=
    INTERFACE_ADDRESS: "10.70.250.76/31"

    # NN757
  - NAME: roy757
    PORT: 51860
    PEER_PUBLIC_KEY: pvHVnAw3uDbWjJcW8+9OoWG9e+Z1UPK8X0lkBWaC5Uc=
    INTERFACE_ADDRESS: "10.70.250.92/31"

    # For myf machupicchu (SN1 migration)
  - NAME: myf
    PORT: 51861
    PEER_PUBLIC_KEY: sgnFN7Uj6acjc9gmDAwD7dGnMGGrP4Hb4OJY53X5RGA=
    INTERFACE_ADDRESS: "10.70.250.78/31"

    # For Andreas Pumberger #12723 (SN1 migration)
  - NAME: andreas
    PORT: 51862
    PEER_PUBLIC_KEY: Q8W/lwGahGN+lNTL5kBHZMTwTW+aoZU5H6hRTJPMnHQ=
    INTERFACE_ADDRESS: "10.70.250.80/31"

    # For Erik #584 (SN1 migration)
  - NAME: erik584
    PORT: 51863
    PEER_PUBLIC_KEY: NkRNuax9PiCs5VOhGe6qJXk/hF5SveCJ8UstFD2DDg4=
    INTERFACE_ADDRESS: "10.70.250.82/31"

    # For Lydon road warrior (laptop)
  - NAME: lydon
    PORT: 51864
    PEER_PUBLIC_KEY: 7//2RfpyEwlGEJsplTywh0TlZm08aSlvY5ADC1/1l3A=
    INTERFACE_ADDRESS: "10.70.250.84/31"

    # For oliver' (SN1 migration)
  - NAME: oliver1
    PORT: 51865
    PEER_PUBLIC_KEY: F0W2Gnn+INb27JpQIxKTwm39MRYU8ZA00985Z7gjl0M=
    INTERFACE_ADDRESS: "10.70.250.86/31"

    # For deploying https://github.com/nycmeshnet/nycmesh-building
  - NAME: ghbuilding
    PORT: 51866
    PEER_PUBLIC_KEY: uJRWbdAgjbUkhmuXb/6JjjIrU1GjOTXtO92uElvS2wY=
    INTERFACE_ADDRESS: "10.70.250.88/31"

    # Richard S
  - NAME: richards
    PORT: 51867
    PEER_PUBLIC_KEY: qoHT9IxkRQzZBHztq/X/MupdShp2R/kpRA8JO2eLbUU=
    INTERFACE_ADDRESS: "10.70.250.90/31"

    # For Zach phone (SN3 migration)
  - NAME: zachphone
    PORT: 51868
    PEER_PUBLIC_KEY: TmUnaXt5LoeFfJWZyTafT/MBQ0RTRBW9yXicGxzi1Qs=
    INTERFACE_ADDRESS: "10.70.250.94/31"

    # For Matthew Boyd Laptop (SN3 migration)
  - NAME: mattlaptop
    PORT: 51869
    PEER_PUBLIC_KEY: 3UVwDc4qofIVcne0fmkp6vp+n55mE329veIXy7Bq1Cc=
    INTERFACE_ADDRESS: "10.70.250.96/31"

    # For Lydon Laptop (SN3 migration)
  - NAME: lydonlaptop
    PORT: 51870
    PEER_PUBLIC_KEY: 2Zi8ePpTkUOoBvAhQQ+cDFxBE/IMLGNF3gV56PgjtlY=
    INTERFACE_ADDRESS: "10.70.250.98/31"
