wireguard_configs:

## OSPF Connections

    # For the super awesome remote hub NN592
  - NAME: nn592
    PORT: 51821
    PEER_PUBLIC_KEY: sD3bVQglZfq2j82or48q+i0R0KdszUPZRkcz4rVqAk8=
    INTERFACE_ADDRESS: "10.70.247.121/30"
    NEIGHBORS: "10.70.247.122"
    TX_LENGTH: 1420
    COST: 99

    # For Andrew Dickinson Amazon VPC
  - NAME: andrewvpc
    PORT: 51825
    PEER_PUBLIC_KEY: 2uMY2He1KCRjnsXnKU4KVD6dfCXzUUxly117aXsZ3kc=
    INTERFACE_ADDRESS: "10.70.247.125/30"
    NEIGHBORS: "10.70.247.126"
    TX_LENGTH: 1366
    COST: 130

    # For Matt B 777
  - NAME: nn777
    PORT: 51827
    PEER_PUBLIC_KEY: KLuwfaUdugySPhNAtOpdBDQeplvt0vaqioWBFtTCcAo=
    INTERFACE_ADDRESS: "10.70.247.129/30"
    NEIGHBORS: "10.70.247.130"
    TX_LENGTH: 1420
    COST: 198
    BFD_ENABLE: true
    BFD_INTERVAL: 500ms
    BFD_MULTIPLIER: 10

    # For Soft Surplus 1417
  - NAME: nn1417
    PORT: 51828
    PEER_PUBLIC_KEY: VGIoIuqIfM+lZt1rgJ9WZzu9n6qn7+YWFn2W/GvmGxo=
    INTERFACE_ADDRESS: "10.70.247.133/30"
    NEIGHBORS: "10.70.247.134"
    TX_LENGTH: 1420
    COST: 96
    BFD_ENABLE: true
    BFD_INTERVAL: 500ms
    BFD_MULTIPLIER: 10

    # For nn7800 CCNY
  - NAME: nn7800
    PORT: 51831
    PEER_PUBLIC_KEY: QPu1xed/4VgghL7QFcYFLgN5c+bw6XfPEFwdg8tebzw=
    INTERFACE_ADDRESS: "10.70.247.137/30"
    NEIGHBORS: "10.70.247.138"
    TX_LENGTH: 1420
    COST: 50
    BFD_ENABLE: true
    BFD_INTERVAL: 500ms
    BFD_MULTIPLIER: 10

    # Monique laptop
  - NAME: moniquelaptop
    PORT: 51833
    PEER_PUBLIC_KEY: LbjNQE6mwaC5v1zlLRDMBqeUC30ta/Cv4xgcW5U46ko=
    INTERFACE_ADDRESS: "10.70.247.141/30"

    # Neel rooftop
  - NAME: neelrooftop
    PORT: 51837
    PEER_PUBLIC_KEY: Szkwoo1JWRVbqVY/I+8ptjW//7WrJQXs0bdGSLymEH4=
    INTERFACE_ADDRESS: "10.70.247.145/30"
    NEIGHBORS: "10.70.247.146"
    TX_LENGTH: 1344
    COST: 10
    BFD_ENABLE: true
    BFD_INTERVAL: 500ms
    BFD_MULTIPLIER: 10

    # NN835 Monroe
  - NAME: nn835
    PORT: 51838
    PEER_PUBLIC_KEY: jnq9yE8dbFDaM23lLPZJp4+9tbNYwvPGPD8KT3+f60w=
    INTERFACE_ADDRESS: "10.70.247.149/30"
    NEIGHBORS: "10.70.247.150"
    TX_LENGTH: 1420
    COST: 97
    BFD_ENABLE: true
    BFD_INTERVAL: 500ms
    BFD_MULTIPLIER: 10

    # NN162 South Slope
  - NAME: nn162
    PORT: 51839
    PEER_PUBLIC_KEY: FaJH/2fG9JgJTxbcMJdLzcAhGZUybQMQNVERhRrUG3c=
    INTERFACE_ADDRESS: "10.70.247.153/30"
    NEIGHBORS: "10.70.247.154"
    TX_LENGTH: 1420
    COST: 85
    BFD_ENABLE: true
    BFD_INTERVAL: 500ms
    BFD_MULTIPLIER: 10

    # For NN890 Astoria Food Pantry VPN
  - NAME: nn890
    PORT: 51840
    PEER_PUBLIC_KEY: food/3hBRJaV1qA9abdZph9UoIV8fnKUVrzMyBGVv0o=
    INTERFACE_ADDRESS: "10.70.247.157/30"
    NEIGHBORS: "10.70.247.158"
    TX_LENGTH: 1420
    COST: 99

    # NN999 Matt B
  - NAME: nn999
    PORT: 51841
    PEER_PUBLIC_KEY: uwQ4Sdy5MFue2wx1f72Ru/HIrlXfV01/e7drrqCvFzY=
    INTERFACE_ADDRESS: "10.70.247.161/30"
    NEIGHBORS: "10.70.247.162"
    TX_LENGTH: 1420
    COST: 200
    BFD_ENABLE: true
    BFD_INTERVAL: 500ms
    BFD_MULTIPLIER: 10

### Road Warriors

    # For James
  - NAME: jameso
    PORT: 51822
    PEER_PUBLIC_KEY: nj5rB0CIL6JUXLvl+oqQXcav2qnr509FzpF30lF8mEY=
    INTERFACE_ADDRESS: "10.70.247.0/31"

    # For Matt
  - NAME: matt
    PORT: 51823
    PEER_PUBLIC_KEY: JQ9/0Ll0oCsq1F5EHXomnoKiaSnvGX9b2RH4KfRq7Us=
    INTERFACE_ADDRESS: "10.70.247.2/31"

    # For JohnB
  - NAME: johnb
    PORT: 51824
    PEER_PUBLIC_KEY: JOHNBcSeEXKV7l6KEi9ktxoKiFh6CymdfZ3ItDZCxRk=
    INTERFACE_ADDRESS: "10.70.247.4/31"

    # For Olivier
  - NAME: olivier
    PORT: 51826
    PEER_PUBLIC_KEY: Kak4TThChfbK+jzzvXsdoVgFvAb082uqI2PIVdCMD1c=
    INTERFACE_ADDRESS: "10.70.247.6/31"

    # Lydon Laptop
  - NAME: lydonlaptop
    PORT: 51829
    PEER_PUBLIC_KEY: 2Zi8ePpTkUOoBvAhQQ+cDFxBE/IMLGNF3gV56PgjtlY=
    INTERFACE_ADDRESS: "10.70.247.8/31"

    # Matt Travel Unifi
  - NAME: mattUnifi
    PORT: 51830
    PEER_PUBLIC_KEY: y4zE2THM/SHEjLIXrs5snKNNQEIXVeWg7MsJ1BLAMUA=
    INTERFACE_ADDRESS: "10.70.247.10/31"

    # Lekhya Road warrior
  - NAME: Lekhya
    PORT: 51832
    PEER_PUBLIC_KEY: 6KuYC/GlvS+TyOenz1wNkRjHXSSjkoACQVYbPPkd4G4=
    INTERFACE_ADDRESS: "10.70.247.12/31"

    # Jason Road warrior
  - NAME: jason
    PORT: 51834
    PEER_PUBLIC_KEY: Q7k2E1wb9DU9kiTAtsu0EIXqyeITtKwQQkmpyA2R208=
    INTERFACE_ADDRESS: "10.70.247.14/31"

    # Matt B Travel Router
  - NAME: MattBGLInet
    PORT: 51835
    PEER_PUBLIC_KEY: voSGH4J7FQJYDrHbue+W9cEIWobwj8Mtry5E6BZ8UTE=
    INTERFACE_ADDRESS: "10.70.247.16/31"

    # For Jimmy laptop
  - NAME: jimmylaptop
    PORT: 51836
    PEER_PUBLIC_KEY: NVIUhbigtj//GpYbcbkMM/XsdpKsbpW2tJwBYU8WEEw=
    INTERFACE_ADDRESS: "10.70.247.18/31"

    # Scott145 Desktop
  - NAME: scottdesktop
    PORT: 51837
    PEER_PUBLIC_KEY: x8xwBczZZCeT1pATaEy4Menv4QuV2xXTnpJb8yt4TU8=
    INTERFACE_ADDRESS: "10.70.247.20/31"

    # Scott145 Laptop
  - NAME: scottlaptop
    PORT: 51838
    PEER_PUBLIC_KEY: IILzKvhJ6DJjRZlbk7fg0sAepeebs9fHgYZpge391Fg=
    INTERFACE_ADDRESS: "10.70.247.22/31"


    ### Site-to-site

    # SN10 -> SN3
  - NAME: sn3
    PORT: 51803
    PEER_PUBLIC_KEY: HCYsMu1Wztk8ape2WP5HYiFZnNpn07guRNvKZw/e0mk=
    PEER_ENDPOINT: "199.170.132.43:51810"
    INTERFACE_ADDRESS: "10.70.183.2/30"
    NEIGHBORS: "10.70.183.1"
    TX_LENGTH: 1420
    COST: 80

    # SN10 -> SN11
  - NAME: sn11
    PORT: 51811
    PEER_PUBLIC_KEY: 5wOBTSB3kH7CdZfBZAw8iomGQbS0POlmOLx2MFmzhFg=
    PEER_ENDPOINT: "208.68.5.2:51810"
    INTERFACE_ADDRESS: "10.70.183.9/30"
    NEIGHBORS: "10.70.183.10"
    TX_LENGTH: 1420
    COST: 92
